<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="EFConfiguration\FormBuilderConfiguration\ActionTypeConfiguration.cs" />
    <Compile Remove="EFConfiguration\FormBuilderConfiguration\AttributeConfiguration.cs" />
    <Compile Remove="EFConfiguration\FormBuilderConfiguration\CssConfiguration.cs" />
    <Compile Remove="EFConfiguration\FormBuilderConfiguration\FieldConfiguration.cs" />
    <Compile Remove="EFConfiguration\FormBuilderConfiguration\FieldTypeConfiguration.cs" />
    <Compile Remove="EFConfiguration\FormBuilderConfiguration\FieldTypeShowConfiguration.cs" />
    <Compile Remove="EFConfiguration\FormBuilderConfiguration\FormGroupConfiguration.cs" />
    <Compile Remove="EFConfiguration\FormBuilderConfiguration\FormGroupTypeConfiguration.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Data\" />
  </ItemGroup>

</Project>
